application: golight-app
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:

- url: /static.*
  static_dir: static

- url: /
  script: routes.app
  login: required

- url: /.*
  script: routes.app
